env:
  browser: yes
  es6: no
extends: semistandard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Phaser: readonly
  PhaserPluginInspector: readonly
  Tweakpane: readonly
  __Global__: readonly
rules:
  no-new: off
